  ## House price prediction

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
train=pd.read_csv('C:/Users/nithi/OneDrive/CSM351/housing/housing.csv')
train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

In [4]:
train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20637 non-null  float64
 3   total_rooms         20635 non-null  float64
 4   total_bedrooms      20429 non-null  float64
 5   population          20628 non-null  float64
 6   households          20630 non-null  float64
 7   median_income       20631 non-null  float64
 8   median_house_value  20632 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [6]:
train.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [7]:
# fig,ax=plt.subplots(figsize=(10,10))
# sns.boxplot(data=train['total_rooms'] ,ax=ax)
# plt.show()

In [8]:
# fig ,ax  = plt.subplots(figsize=(15,15))
# sns.boxplot(data=train,ax=ax)

In [9]:
# sns.scatterplot(x=train['population'],y=train['median_income'])

In [10]:
(train.isnull().sum()/train.shape[0])*100

longitude             0.000000
latitude              0.000000
housing_median_age    0.014535
total_rooms           0.024225
total_bedrooms        1.022287
population            0.058140
households            0.048450
median_income         0.043605
median_house_value    0.038760
dtype: float64

In [11]:
# sns.distplot(train['housing_median_age'])
# # median

In [12]:
# sns.distplot(train['total_rooms'])
# #median

In [13]:
# sns.distplot(train['total_bedrooms'])
# # median

In [14]:
# sns.distplot(train['population'])
# #median

In [15]:
# sns.distplot(train['households'])
#median

In [16]:
# sns.distplot(train['median_income'])
# #median

In [17]:
# fig ,ax  = plt.subplots(figsize=(50,50))
# sns.boxplot(data=train,ax=ax)

In [18]:
# fig,ax=plt.subplots(figsize=(8,8))
# sns.boxplot(data=train['longitude'] ,ax=ax)
# plt.show()

In [19]:
# plt.figure(figsize=(5,5))
# sns.heatmap(train.corr(),annot = True)
# plt.show()

In [20]:
train.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20637.000000,20635.000000,20429.000000,20628.000000,20630.000000,20631.000000,20632.000000
mean,-119.569704,35.631861,28.639046,2635.499443,537.869352,1425.440760,499.607465,3.870831,206870.509936
std,2.003532,2.135952,12.585640,2181.039708,421.384250,1132.601922,382.356098,1.900014,115402.351214
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.500000,296.000000,787.000000,280.000000,2.563100,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534900,179700.000000
75%,-118.010000,37.710000,37.000000,3147.500000,647.000000,1725.000000,605.000000,4.743400,264825.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [21]:
train.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [22]:

# plt.bar(train.index,train['median_income'])
# plt.xlabel("median income")
# plt.show()

In [23]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy = 'median')
train['housing_median_age']=imputer.fit_transform(train[['housing_median_age']])
train['total_rooms']=imputer.fit_transform(train[['total_rooms']])
train['total_bedrooms']=imputer.fit_transform(train[['total_bedrooms']])
train['population']=imputer.fit_transform(train[['population']])
train['households']=imputer.fit_transform(train[['households']])
train['median_income']=imputer.fit_transform(train[['median_income']])
train['median_house_value']=imputer.fit_transform(train[['median_house_value']])

In [24]:
train.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [25]:
(train.isnull().sum()/train.shape[0])*100

longitude             0.0
latitude              0.0
housing_median_age    0.0
total_rooms           0.0
total_bedrooms        0.0
population            0.0
households            0.0
median_income         0.0
median_house_value    0.0
dtype: float64

In [26]:
train.drop_duplicates()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

In [27]:
train.dropna()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

In [28]:
(train.isnull().sum()/train.shape[0])*100

longitude             0.0
latitude              0.0
housing_median_age    0.0
total_rooms           0.0
total_bedrooms        0.0
population            0.0
households            0.0
median_income         0.0
median_house_value    0.0
dtype: float64

In [29]:
# plt.bar(train.index,train['median_income'])
# plt.show()

In [30]:
# sns.scatterplot(x=train['population'],y=train['median_income'])

In [31]:
# sns.pairplot(train)

In [32]:
# numerical_columns = train.select_dtypes(include=['number']).columns

In [33]:
numerical_columns=train.columns

In [34]:
numerical_columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [35]:
column=['longitude', 'latitude', 'housing_median_age', 'total_rooms','total_bedrooms', 'population', 'households', 'median_income','median_house_value']

In [36]:
x=train.iloc[:,0:-1]
y=train.iloc[:,-1]

In [37]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [38]:
# fig, ax = plt.subplots(figsize = (15, 15))

In [39]:
x

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462
...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886

In [40]:
# 11.	from sklearn.preprocessing import StandardScaler
# 12.	model=StandardScaler()
# 13.	x_scaled=model.fit_transform(new_x_data)
# 14.	x_scaled

In [41]:
# for col in column:
#     q1=x[col].quantile(0.25)
#     q3=x[col].quantile(0.75)
#     iqr=q3-q1
#     lower=q1 - 1.5 * iqr
#     upper=q3 + 1.5 * iqr
#     mask=(x[col] >= lower) & (x[col] <= upper)
#     new_x_data=x[mask]
#     new_y_data=y[mask]

In [42]:
# for col in column:
#     new_x_data.reset_index(drop=True, inplace=True)
#     new_y_data.reset_index(drop=True, inplace=True)
#     q=new_x_data[col].quantile(0.90)
#     mask=new_x_data[col] < q
#     new_xx_data=new_x_data[mask]
#     new_yy_data=new_y_data[mask]

In [43]:
# coll=['total_rooms','total_bedrooms', 'population', 'households']

In [44]:
# for col in coll:
#     q1=new_xx_data[col].quantile(0.25)
#     q3=new_xx_data[col].quantile(0.60)
#     iqr=q3-q1
#     lower=q1 - 1.5 * iqr
#     upper=q3 + 1.5 * iqr
#     mask=(new_xx_data[col] >= lower) & (new_xx_data[col] <= upper)
#     x_data=new_xx_data[mask]
#     y_data=new_yy_data[mask]

In [45]:
# y_data

In [46]:
# for col in coll:
#     x_data.reset_index(drop=True, inplace=True)
#     y_data.reset_index(drop=True, inplace=True)
#     q=x_data[col].quantile(0.80)
#     mask=x_data[col] < q
#     xx=x_data[mask]
#     yy=y_data[mask]

In [47]:
# yy

In [48]:
# coll=['total_rooms','total_bedrooms', 'population']

In [49]:
# for i  in coll:
#     q1=xx[i].quantile(0.25)
#     q3=xx[i].quantile(0.60)
#     iqr=q3-q1
#     lower=q1 - 1.5 * iqr
#     upper=q3 + 1.5 * iqr
#     mask=(xx[i] >= lower) & (xx[i] <= upper)
#     x_data=xx[mask]
#     y_data=yy[mask]
#     x_data.reset_index(drop=True, inplace=True)
#     y_data.reset_index(drop=True, inplace=True)
#     q=x_data[col].quantile(0.80)
#     mask=x_data[col] < q
#     x=x_data[mask]
#     y=y_data[mask]

In [50]:
# q1=x['total_rooms'].quantile(0.25)
#     q3=x['total_rooms'].quantile(0.60)
#     iqr=q3-q1
#     lower=q1 - 1.5 * iqr
#     upper=q3 + 1.5 * iqr
#     mask=(x['total_rooms'] >= lower) & (x['total_rooms'] <= upper)
#     x_data=x[mask]
#     y_data=y[mask]
#     x_data.reset_index(drop=True, inplace=True)
#     y_data.reset_index(drop=True, inplace=True)
#     q=x_data['total_rooms'].quantile(0.80)
#     mask=x_data['total_rooms'] < q
#     a=x_data[mask]
#     b=y_data[mask]

In [51]:
# y_data

In [52]:
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
# sns.barplot(data=new_xx_data,x="population",y="population")

In [54]:
# from sklearn.preprocessing import StandardScaler
# model=StandardScaler()
# x_scaled=model.fit_transform(xx)
# x_scaled=pd.DataFrame(x_scaled)

In [55]:
# fig, ax = plt.subplots(figsize = (7, 7))
# sns.boxplot(data = a['total_rooms'], ax=ax)

In [56]:
# fig, ax = plt.subplots(figsize = (15, 15))
# sns.boxplot(data = a[, ax=ax)

In [57]:
#

In [58]:
# # # Set the size of the plot
# plt.figure(figsize=(5,5))

# # Create a heatmap to visualize the correlation matrix
# sns.heatmap(a, fmt=".2f", cmap='coolwarm', cbar_kws={"shrink": .8})

# # Title for the heatmap
# plt.title('Correlation Matrix Heatmap', fontsize=16)

# # Show the plot
# plt.show()

In [59]:
# plt.figure(figsize=(7,7))
# plt.hist(x=a["housing_median_age"],bins=30)
# plt.show()

In [60]:
# sns.kdeplot(a["housing_median_age"])
# plt.show()

In [61]:
# a

In [62]:
# plt.figure(figsize=(6, 6))
# sns.histplot(x=a['housing_median_age'],y=a['median_income'], data=a)
# plt.title(' housing_median_age vs median_income')
# plt.xlabel('housing_median_age')
# plt.ylabel('median_income')
# plt.show()

In [63]:
# sns.countplot(a['total_bedrooms'])
# plt.show()

In [64]:
# plt.figure(figsize=(6, 6))
# sns.scatterplot(x=a['longitude'],y=a['latitude'], data=a)

In [65]:
# # Scatter plot

# plt.figure(figsize=(10, 6))
# sns.scatterplot(x=a['housing_median_age'],y=a['median_income'], data=a)
# plt.title('Scatter Plot of housing_median_age vs median_income')
# plt.xlabel('housing_median_age')
# plt.ylabel('median_income')
# plt.show()

In [66]:
# a

In [67]:
# Pie chart
# plt.figure(figsize=(7, 7))
# a['housing_median_age'].value_counts().plot.pie(autopct='%.2f%%')
# plt.title('housing_median_age')
# plt.ylabel('')
# plt.show()

In [68]:

# sns.countplot(a['total_bedrooms'])
# plt.show()

In [69]:
# (train.isnull().sum()/train.shape[0])*100

In [70]:
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming 'tips' is your DataFrame
# sns.scatterplot(x=a["median_income"], y=a["housing_median_age"], hue=a["total_bedrooms"], data=a)

# # Add titles and labels for better understanding (optional)
# plt.title('Scatter Plot of median_incomel vs housing_median_age with total_bedrooms Hue')  # Title for the plot
# plt.xlabel('median_income')  # Label for x-axis
# plt.ylabel('housing_median_age')  # Label for y-axis
# plt.show()

In [71]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor

In [72]:
# x=x.iloc[:,:-1]
# y=y

In [73]:

# a

In [74]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [75]:
x

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462
...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886

In [76]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
model=RandomForestRegressor(100)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R² Score:", r2)

Mean Squared Error: 2542305672.5499964
R² Score: 0.8093064615748788

In [77]:
model1=DecisionTreeRegressor()
model1.fit(x_train,y_train)
y_pred1=model1.predict(x_test)

In [78]:
mse = mean_squared_error(y_test, y_pred1)
r2 = r2_score(y_test, y_pred1)
print("Mean Squared Error:", mse)
print("R² Score:", r2)

Mean Squared Error: 4765804821.070737
R² Score: 0.6425259973314214

In [79]:
# plt.plot(y_test,'+')
# plt.plot(y_pred,'*')
# plt.show()

In [80]:
# sns.pairplot(a)

In [81]:
import joblib

In [82]:
joblib.dump(model,"House_price_prediction.pkl")

['House_price_prediction.pkl']